-- ============================================
-- PART A: DATABASE SCHEMA CREATION
-- ============================================
-- This script creates the initial docs table
-- for storing scientific articles from PubMed Central

-- Drop table if exists (for clean setup)
DROP TABLE IF EXISTS docs CASCADE;

-- Create the docs table
CREATE TABLE docs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    abstract TEXT
);

-- Add comments for documentation
COMMENT ON TABLE docs IS 'Stores scientific articles with title and abstract fields';
COMMENT ON COLUMN docs.id IS 'Primary key, auto-generated';
COMMENT ON COLUMN docs.title IS 'Article title from PubMed';
COMMENT ON COLUMN docs.abstract IS 'Article abstract from PubMed';

