-- ============================================
-- COMPLETE SETUP SCRIPT FOR SUPABASE
-- ============================================
-- Run this in Supabase SQL Editor
-- This will create schema, setup FTS, and prepare for data loading

-- Step 1: Create schema (if not exists)
DROP TABLE IF EXISTS docs CASCADE;

CREATE TABLE docs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    abstract TEXT
);

-- Step 2: Add TSVECTOR columns
ALTER TABLE docs 
ADD COLUMN IF NOT EXISTS title_tsv TSVECTOR,
ADD COLUMN IF NOT EXISTS abstract_tsv TSVECTOR;

-- Step 3: Create trigger function
CREATE OR REPLACE FUNCTION update_docs_tsvector()
RETURNS TRIGGER AS $$
BEGIN
    NEW.title_tsv := to_tsvector('english', COALESCE(NEW.title, ''));
    NEW.abstract_tsv := to_tsvector('english', COALESCE(NEW.abstract, ''));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Step 4: Create trigger
DROP TRIGGER IF EXISTS docs_tsvector_update ON docs;

CREATE TRIGGER docs_tsvector_update
    BEFORE INSERT OR UPDATE ON docs
    FOR EACH ROW
    EXECUTE FUNCTION update_docs_tsvector();

-- Step 5: Create GIN indexes
CREATE INDEX IF NOT EXISTS idx_docs_title_tsv ON docs USING GIN (title_tsv);
CREATE INDEX IF NOT EXISTS idx_docs_abstract_tsv ON docs USING GIN (abstract_tsv);
CREATE INDEX IF NOT EXISTS idx_docs_combined_tsv ON docs 
USING GIN ((title_tsv || abstract_tsv));

-- Step 6: Analyze
ANALYZE docs;

-- Verify setup
SELECT 
    'Schema created successfully!' AS status,
    COUNT(*) AS existing_docs
FROM docs;

